In [1]:
import pandas as pd

In [2]:
name=pd.Series(["小陈", "小李", "小王", "小张", "小赵", "小周"],index=["001", "002", "003", "004", "005", "006"])
print(name)
gender=pd.Series(["女", "女", "男", "男", "女", "男"],index=["006", "005", "004", "003", "002", "001"])
print(gender)
height=pd.Series([172.5, 168.0, 178.2, 181.3, 161.7],index=["001", "002", "003", "004", "005"])
print(height)

001    小陈
002    小李
003    小王
004    小张
005    小赵
006    小周
dtype: object
006    女
005    女
004    男
003    男
002    女
001    男
dtype: object
001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
dtype: float64

In [4]:
students=pd.DataFrame({"姓名":name,"性别":gender,"身高":height,})
students

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7
006  小周  女    NaN

In [5]:
print(students.index)
print(students.columns)

Index(['001', '002', '003', '004', '005', '006'], dtype='object')
Index(['姓名', '性别', '身高'], dtype='object')

In [6]:
students.T

      001    002    003    004    005  006
姓名     小陈     小李     小王     小张     小赵   小周
性别      男      女      男      男      女    女
身高  172.5  168.0  178.2  181.3  161.7  NaN

In [11]:
students.loc["003"]

姓名       小王
性别        男
身高    178.2
Name: 003, dtype: object

In [17]:
import tkinter as tk

class QuickSnakeFill:
    def __init__(self, n=10, size=40):
        self.n, self.size = n, size
        self.root = tk.Tk()
        self.root.title("蛇形填数")
    
        self.canvas = tk.Canvas(self.root, width=n*size, height=n*size, bg="white")
        self.canvas.pack(padx=10, pady=10)

        self.matrix = [[0] * n for _ in range(n)]
        self.dirs = [(0, 1), (1, 0), (0, -1), (-1, 0)] 
        self.x, self.y, self.d, self.curr_num = 0, 0, 0, 1

        self.step()
        self.root.mainloop()

    def step(self):
        if self.curr_num > self.n * self.n: return 

        x1, y1 = self.y * self.size, self.x * self.size
        self.canvas.create_rectangle(x1, y1, x1+self.size, y1+self.size, fill="#ADD8E6", outline="gray")
        self.canvas.create_text(x1 + self.size/2, y1 + self.size/2, text=str(self.curr_num), font=("Arial", 12, "bold"))

        self.matrix[self.x][self.y] = self.curr_num
        self.curr_num += 1
        

        dx, dy = self.dirs[self.d]
        nx, ny = self.x + dx, self.y + dy
        if not (0 <= nx < self.n and 0 <= ny < self.n and self.matrix[nx][ny] == 0):
            self.d = (self.d + 1) % 4
            dx, dy = self.dirs[self.d]
            nx, ny = self.x + dx, self.y + dy
            
        self.x, self.y = nx, ny
        self.root.after(100, self.step)

if __name__ == "__main__":
    QuickSnakeFill(10)

In [18]:
students[(students["身高"]>165)&(students["性别"]=="女")]

     姓名 性别     身高
002  小李  女  168.0

In [19]:
students.head()

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

In [22]:

students=pd.DataFrame({"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},
 "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},
 "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},
 "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
 "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},
 "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}
 }).T

students

     姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92