In [1]:
import pandas as pd
data = {    
    "姓名": ["张海洋", "孟晓舟", "毛不易", "司浩然", "潘特", "胡丹", "杜威伟", "苏晓", "胡丹", "路啸"],
    "年龄": [68, 34, 16, 18, 44, 52, 19, 32, 52, 22],
    "体重": ["70公斤", "154斤", "76公斤", "78公斤", "198斤", "189斤", "56公斤", "78公斤", "189斤", "45公斤"],
    "性别": ["m", "f", "f", "m", "f", "f", "f", "m", "女", "m"],
    "00~06": [72, 85, 65, 78, 69, 68, 71, 78, 68, 92],
    "06~12": [69, 84, 69, 79, None, 75, 78,None, 75, 95],
    "12~18": [71, 76, 72, 72, 75, 72, 75, 75, 131, 87]
}
df = pd.DataFrame(data)
df

    姓名  年龄    体重 性别  00~06  06~12  12~18
0  张海洋  68  70公斤  m     72   69.0     71
1  孟晓舟  34  154斤  f     85   84.0     76
2  毛不易  16  76公斤  f     65   69.0     72
3  司浩然  18  78公斤  m     78   79.0     72
4   潘特  44  198斤  f     69    NaN     75
5   胡丹  52  189斤  f     68   75.0     72
6  杜威伟  19  56公斤  f     71   78.0     75
7   苏晓  32  78公斤  m     78    NaN     75
8   胡丹  52  189斤  女     68   75.0    131
9   路啸  22  45公斤  m     92   95.0     87

In [2]:
#2、查看有哪些列有缺失值。

In [3]:
print("每列缺失值数量：")
print(df.isnull().sum())

print("\n哪些列存在缺失值：")
print(df.isnull().any())

每列缺失值数量：
姓名       0
年龄       0
体重       0
性别       0
00~06    0
06~12    2
12~18    0
dtype: int64

哪些列存在缺失值：
姓名       False
年龄       False
体重       False
性别       False
00~06    False
06~12     True
12~18    False
dtype: bool

In [4]:
#3、缺失值可以用平均值替代。

In [5]:
df["06~12"].mean()

np.float64(78.0)

In [6]:
df["06~12"] = df["06~12"].fillna(df["06~12"].mean())
df

    姓名  年龄    体重 性别  00~06  06~12  12~18
0  张海洋  68  70公斤  m     72   69.0     71
1  孟晓舟  34  154斤  f     85   84.0     76
2  毛不易  16  76公斤  f     65   69.0     72
3  司浩然  18  78公斤  m     78   79.0     72
4   潘特  44  198斤  f     69   78.0     75
5   胡丹  52  189斤  f     68   75.0     72
6  杜威伟  19  56公斤  f     71   78.0     75
7   苏晓  32  78公斤  m     78   78.0     75
8   胡丹  52  189斤  女     68   75.0    131
9   路啸  22  45公斤  m     92   95.0     87

In [7]:
#统一数据类型，把心率统一为整数型。

In [8]:
df["06~12"] = df["06~12"].round().astype(int)

In [9]:
df

    姓名  年龄    体重 性别  00~06  06~12  12~18
0  张海洋  68  70公斤  m     72     69     71
1  孟晓舟  34  154斤  f     85     84     76
2  毛不易  16  76公斤  f     65     69     72
3  司浩然  18  78公斤  m     78     79     72
4   潘特  44  198斤  f     69     78     75
5   胡丹  52  189斤  f     68     75     72
6  杜威伟  19  56公斤  f     71     78     75
7   苏晓  32  78公斤  m     78     78     75
8   胡丹  52  189斤  女     68     75    131
9   路啸  22  45公斤  m     92     95     87

In [10]:
# 统一性别：把“男”→m，“女”→f
df['性别'] = df['性别'].replace({'男': 'm', '女': 'f'})

# 查看修改后的性别列
print("统一后的性别列：")
print(df['性别'])

统一后的性别列：
0    m
1    f
2    f
3    m
4    f
5    f
6    f
7    m
8    f
9    m
Name: 性别, dtype: str

In [11]:
df

    姓名  年龄    体重 性别  00~06  06~12  12~18
0  张海洋  68  70公斤  m     72     69     71
1  孟晓舟  34  154斤  f     85     84     76
2  毛不易  16  76公斤  f     65     69     72
3  司浩然  18  78公斤  m     78     79     72
4   潘特  44  198斤  f     69     78     75
5   胡丹  52  189斤  f     68     75     72
6  杜威伟  19  56公斤  f     71     78     75
7   苏晓  32  78公斤  m     78     78     75
8   胡丹  52  189斤  f     68     75    131
9   路啸  22  45公斤  m     92     95     87

In [12]:
# 1. 提取纯数字
num_weight = df['体重'].str.extract(r'(\d+)').astype(float)

# 2. 空列表
new_weights = []

# 3. 循环 + if 判断单位
for i in range(len(df)):
    w = df['体重'].iloc[i]
    
   
    num = num_weight.iloc[i,0]
    
    if "公斤" in w:
        kg = num
    else:
        kg = num*0.5
    
    new_weights.append(int(kg))

# 4. 覆盖
df['体重'] = new_weights

In [13]:
df

    姓名  年龄  体重 性别  00~06  06~12  12~18
0  张海洋  68  70  m     72     69     71
1  孟晓舟  34  77  f     85     84     76
2  毛不易  16  76  f     65     69     72
3  司浩然  18  78  m     78     79     72
4   潘特  44  99  f     69     78     75
5   胡丹  52  94  f     68     75     72
6  杜威伟  19  56  f     71     78     75
7   苏晓  32  78  m     78     78     75
8   胡丹  52  94  f     68     75    131
9   路啸  22  45  m     92     95     87

In [14]:
check_cols = ["00~06", "06~12", "12~18"]

for col in check_cols:
    mean_val = df[col].mean()
    
    # 找出异常
    abnormal = df[(df[col] > mean_val + 30) | (df[col] < mean_val - 30)]
    
    print(f"列：{col}  平均值：{mean_val:.1f}")
    if not abnormal.empty:
        print("异常数据：")
        print(abnormal[["姓名", col]])
    else:
        print("无异常")
    print("-"*40)

列：00~06  平均值：74.6
无异常
----------------------------------------
列：06~12  平均值：78.0
无异常
----------------------------------------
列：12~18  平均值：80.6
异常数据：
   姓名  12~18
8  胡丹    131
----------------------------------------

In [15]:
check_cols = ["00~06", "06~12", "12~18"]

for col in check_cols:
    mean_val = df[col].mean()
    mask = (df[col] > mean_val + 30) | (df[col] < mean_val - 30)
    df.loc[mask, col] = int(round(mean_val))

df

    姓名  年龄  体重 性别  00~06  06~12  12~18
0  张海洋  68  70  m     72     69     71
1  孟晓舟  34  77  f     85     84     76
2  毛不易  16  76  f     65     69     72
3  司浩然  18  78  m     78     79     72
4   潘特  44  99  f     69     78     75
5   胡丹  52  94  f     68     75     72
6  杜威伟  19  56  f     71     78     75
7   苏晓  32  78  m     78     78     75
8   胡丹  52  94  f     68     75     81
9   路啸  22  45  m     92     95     87