In [1]:
import pandas as pd

data = {
    "客户编号": [1, 1, 2, 2, 3, 4, 4, 5],
    "商家": ["云海肴", "丰收日", "云海肴", "丰收日", "西秦美食", "西秦美食", "丰收日", "云海肴"],
    "品名": ["过桥米线", "小炒肉", "过桥米线", "红烧肉", "羊肉汤", "肉夹馍", "牛肉粒", "汽锅鸡"],
    "数量": [2, 1, 1, 1, 1, 2, 1, 1],
    "单价": [49, 38, 49, 68, 33, 18, 48, 88]
}

df1 = pd.DataFrame(data)
df1

   客户编号    商家    品名  数量  单价
0     1   云海肴  过桥米线   2  49
1     1   丰收日   小炒肉   1  38
2     2   云海肴  过桥米线   1  49
3     2   丰收日   红烧肉   1  68
4     3  西秦美食   羊肉汤   1  33
5     4  西秦美食   肉夹馍   2  18
6     4   丰收日   牛肉粒   1  48
7     5   云海肴   汽锅鸡   1  88

In [2]:
import pandas as pd

# 构造数据
data = {
    "客户编号": [1, 2, 3, 4, 5],
    "姓名": ["张洋", "段小海", "李景鹏", "李亮", "王霞"],
    "性别": ["男", "女", "男", "男", "女"],
    "地址": ["绥化学院9公寓401", "绥化学院4公寓201", "绥化学院9公寓501", "绥化学院9公寓301", "绥化学院4公寓301"]
}

df2 = pd.DataFrame(data)
df2

   客户编号   姓名 性别          地址
0     1   张洋  男  绥化学院9公寓401
1     2  段小海  女  绥化学院4公寓201
2     3  李景鹏  男  绥化学院9公寓501
3     4   李亮  男  绥化学院9公寓301
4     5   王霞  女  绥化学院4公寓301

In [3]:
user_order = pd.merge(df1, df2, on="客户编号")
user_order

   客户编号    商家    品名  数量  单价   姓名 性别          地址
0     1   云海肴  过桥米线   2  49   张洋  男  绥化学院9公寓401
1     1   丰收日   小炒肉   1  38   张洋  男  绥化学院9公寓401
2     2   云海肴  过桥米线   1  49  段小海  女  绥化学院4公寓201
3     2   丰收日   红烧肉   1  68  段小海  女  绥化学院4公寓201
4     3  西秦美食   羊肉汤   1  33  李景鹏  男  绥化学院9公寓501
5     4  西秦美食   肉夹馍   2  18   李亮  男  绥化学院9公寓301
6     4   丰收日   牛肉粒   1  48   李亮  男  绥化学院9公寓301
7     5   云海肴   汽锅鸡   1  88   王霞  女  绥化学院4公寓301

In [4]:
result = user_order[user_order["品名"] == "过桥米线"]["姓名"]
result

0     张洋
2    段小海
Name: 姓名, dtype: str

In [5]:
result1 = user_order[(user_order["商家"] == "云海肴") | (user_order["商家"] == "丰收日")]["姓名"].drop_duplicates() 
result1

0     张洋
2    段小海
6     李亮
7     王霞
Name: 姓名, dtype: str

In [6]:
user_order["小计"] = user_order["数量"] * user_order["单价"]
user_order

   客户编号    商家    品名  数量  单价   姓名 性别          地址  小计
0     1   云海肴  过桥米线   2  49   张洋  男  绥化学院9公寓401  98
1     1   丰收日   小炒肉   1  38   张洋  男  绥化学院9公寓401  38
2     2   云海肴  过桥米线   1  49  段小海  女  绥化学院4公寓201  49
3     2   丰收日   红烧肉   1  68  段小海  女  绥化学院4公寓201  68
4     3  西秦美食   羊肉汤   1  33  李景鹏  男  绥化学院9公寓501  33
5     4  西秦美食   肉夹馍   2  18   李亮  男  绥化学院9公寓301  36
6     4   丰收日   牛肉粒   1  48   李亮  男  绥化学院9公寓301  48
7     5   云海肴   汽锅鸡   1  88   王霞  女  绥化学院4公寓301  88

In [7]:
per_customer_total = user_order.groupby(["客户编号","姓名"])["小计"].sum()
print("每位客户订餐总金额：")
print(per_customer_total)

# 2. 所有订单总金额
all_total = user_order["小计"].sum()
print(f"\n所有订单总金额：{all_total}")

每位客户订餐总金额：
客户编号  姓名
1     张洋     136
2     段小海    117
3     李景鹏     33
4     李亮      84
5     王霞      88
Name: 小计, dtype: int64

所有订单总金额：458

In [8]:
shop_result = user_order.groupby("商家").agg(
    订单数量=("小计", "count"),    # 统计订单笔数
    平均金额=("小计", "mean")     # 统计平均金额
)

print("每个商家的订单数量和平均金额：")
print(shop_result)

每个商家的订单数量和平均金额：
      订单数量       平均金额
商家
丰收日      3  51.333333
云海肴      3  78.333333
西秦美食     2  34.500000

In [9]:
shops = user_order["商家"].unique()
print("订单来自的商家：")
print(shops)

订单来自的商家：
<StringArray>
['云海肴', '丰收日', '西秦美食']
Length: 3, dtype: str

In [10]:
result_df = user_order[["姓名", "品名", "数量", "小计"]]

# 2. 按 小计 降序排序（金额从大到小）
result_df = result_df.sort_values(by="小计", ascending=False)

# 输出结果
print("按小计降序排序后：")
print(result_df)

按小计降序排序后：
    姓名    品名  数量  小计
0   张洋  过桥米线   2  98
7   王霞   汽锅鸡   1  88
3  段小海   红烧肉   1  68
2  段小海  过桥米线   1  49
6   李亮   牛肉粒   1  48
1   张洋   小炒肉   1  38
5   李亮   肉夹馍   2  36
4  李景鹏   羊肉汤   1  33